apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: simple-nodejs-app-xgeq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wpsm-tenant/nodejs-users/simple-nodejs-app-xgeq@sha256:b4413395a58a514f0001ad78bb269b22b71ccf083b0bb60d6a43255837aa48f3
        name: my-nodejs
        resources: {}
status: {}
